### PR TITLE
more stability for ESP8266

### PR DESCRIPTION
**Pull request by el3ctrician**
in case of esp8266, calling the begin in constructor causing the esp to crash see this [issue](https://www.esp8266.com/viewtopic.php?f=27&t=5929) and [this also](https://github.com/bogde/HX711/issues/73)

added some illustration example also and a keywords file

### CODE REVIEW

**Comment by amotl** [comment]
Hi @bogde,

parts of the changes submitted by @el3ctrician look like they are related to #29 and the corresponding part of the documentation

> See the example in examples/HX711SerialBegin. Please don't use examples/HX711Serial anymore. It is deprecated because the pin definition within the constructor is not timing safe. (#29)

I would recommend removing the non-timing-safe variant completely from the code as it keeps on popping up here, especially as the ESP MCUs are gaining more and more popularity, which leads to different attempts in solving the crashes experienced there. See also #76 and maybe others.

Thanks,
Andreas.

**Comment by bogde** [comment]
Commit was merged. Thank you!

**Comment by amotl** [comment]
Hi @bogde,

thanks for addressing some of these aspects by https://github.com/bogde/HX711/issues/119#issuecomment-456121400.

However, I really would aim at finally removing the problematic constructor altogether and especially would amend the [**ESP8266** example](https://github.com/bogde/HX711/blob/efcf6abb/examples/HX711ESP8266/HX711ESP8266.ino) accordingly.

May we humbly ask whether you would accept an appropriate pull request also emphasizing the breaking change in the documentation appropriately?

Thanks,
Andreas.

**Comment by el3ctrician** [comment]
@amotl @bogde  if you need any help am avilable to work on it during the weekends. Just let me know

**Comment by amotl** [comment]
Dear Ahmad,

assuming you might exactly know what we are talking about, I would be **very** happy if you would take this. Just was rambling around here to check whether @bogde would even consider this change.

## Background
In the advent of [modern libraries for reading the HX711 ADC](https://community.hiveeyes.org/t/modern-libraries-for-reading-the-hx711-adc/1375) (which we are also interested in), I **really** would like to give the well known HX711 library by @bogde here some love as it is still the canonical place to go when reading the HX711 ADC and has a huge audience already.

While we successfully run this library on ESP8266 MCUs already, I would especially like to go into checking compatibility with the ESP32 in the long run. So I thought about bringing this topic up here.

So, if you would like to spend some time on this library, we would appreciate this very much, @el3ctrician.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Ahmad,

while being at it, may I humbly ask you to make the busy loops around the code safe for ESP usage like #120 and friends coming up here frequently?

Thanks in advance,
Andreas.

**Comment by amotl** [comment]
Hi Bogdan and Ahmad,

just wanted to let you know that we managed to make a start in the dry dock [1] and will follow up letting you know whether this will actually compile and work on real hardware.

With kind regards,
Andreas.

[1] https://github.com/hiveeyes/HX711/tree/spring-cleaning

**Pull request merged**
